meals/urls.py
from django.urls import path
from . import views

app_name="meals"

urlpatterns =[
    path("",views.meal_list,name="meal_list"),
    path("<slug:slug>",views.meal_detail,name="meal_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("meals.urls",namespace="meals")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "category"
        verbose_name_plural ="categories"



class Meals(models.Model):
    name=models.CharField(max_length=25)
    description=models.TextField()
    category=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    people = models.PositiveBigIntegerField()
    price=models.DecimalField(max_digits=5,decimal_places=2)
    preperation_time=models.IntegerField()
    image=models.ImageField(upload_to="meals/")
    slug=models.SlugField(blank=True,null=True)
    
    # slugify the name
    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals,self).save(*args, **kwargs)
    # call
    def __str__(self):
        return f"{self.name}"

    # meta
    class Meta:
        verbose_name = "meal"
        verbose_name_plural ="meals"

meals/views.py
from django.shortcuts import render
from .models import Meals,Category
# Create your views here.

def meal_list(request):
    context={
        "meal_lists":Meals.objects.all(),
        "name":"Meal List",
        "categories":Category.objects.all
    }
    return render(request,"meals/meal_list.html",context)
    
def meal_detail(request,slug):
    meal_detail=Meals.objects.get(slug=slug)
    context={
        "meal_detail":meal_detail,
        "name":"Meal Details"
        }
    return render(request,"meals/meal_detail.html",context)

meals/templates/meals/base.html
{% load static %}
<html lang="en">
    <head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-144351462-1"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-144351462-1');
        </script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <title>Meals</title>
         {{ form.media }}
    </head>
<body class="banner">
{% include 'meals/navbar.html' %}
{% block content %}

{% endblock %}
{%block scripts%}
<script src="{%static 'js/main.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
<script src="https://assets.awwwards.com/dist/js/vendor.13df77655f5689a9b532.js" defer></script>
            <script src="https://assets.awwwards.com/dist/js/home.2734a967c43d3d4952c9.js" defer></script>
    
            <!-- <script>
        if('serviceWorker' in navigator) {
            window.addEventListener('load', function() {
                navigator.serviceWorker.register('/sw.js');
            });
        }
            </script> -->
{%endblock%}
</body>
</html>

meals/templates/meals/index.html
{%extends 'meals/base.html'%}
{%load static%}
{%block content%}


{%endblock%}

meals/templates/meals/meal_detail.html
{%extends 'meals/base.html'%}
{%load static%}
{%block content%}
<div class="container">
    <h1 class="text-center">{{name}}</h1>
    <a href="{%url 'meals:meal_list'%}" class="btn btn-sm btn-outline-info">Back</a>
   <div class="row">
       <div class="col-md-3"></div>
       <div class="col-md-6">
         
        <div class="card my-2 meal_details">
            <img src="{{meal_detail.image.url}}"  alt="{{meal_detail.image.url}}" class="img-fluid img-responsive">
            <div class="card-body">
                <h2 class="">{{meal_details.name}}</h2>
                <p class="lead">Description: {{meal_detail.description}}</p>
                <p class="lead">People to be served: {{meal_detail.people}}</p>
                <p class="lead">Price: {{meal_detail.price}}</p>
                <p class="lead">Preperation Time: {{meal_detail.preperation_time}} minutes</p>
                <p class="lead">Price: Kshs {{meal_detail.price}}</p>
              <a class="btn btn-primary">Button</a>
            </div>
          </div>
       </div>
       <div class="col-md-3"></div>
   </div>
</div>


{%endblock%}

meals/templates/meals/meal_list.html
{%extends 'meals/base.html'%}
{%load static%}
{%block content%}
<div class="container">
    <!-- categories of the available meals-->
    {% for category in categories %}
    <div class="categories">
        <ul class="">
                <li class="nav-item"><a href="" class="cats">{{category.name}}</a></li>
        </ul>
        {% endfor %}
    </div>
    <h1>{{name}}</h1>
    <!-- available meals -->
    {%for meal in meal_lists%}
    <h2 class=""><a href="{% url 'meals:meal_detail' meal.slug%}">{{meal.name}}</a></h2>
    {%endfor%}
    
    
</div>

{%endblock%}